# Dependencies
highlighter:         rouge

# Permalinks
permalink:           pretty

# Setup
title:            Thomas Teoh
tagline:          'veterinarian, research, data, epi, design, also other things'
description:      'Life as a veterinarian in research with a dog named Quaver.'
url:              http://www.tteoh.com
baseurl:          /
imgurl:           /public/images/
paginate:         5

author:
  name:           'Thomas Teoh'
  url:            https://www.twitter.com/tteoh
  email:          me@tteoh.com

# Custom vars
version:          1.0.0
