# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            tteoh
tagline:          'in which Thomas talks about things'
description:      'A sporadically updated log about thoughts, learning, research and life as a veterinarian in the beautiful city of Melbourne, Australia.'
url:              http://www.tteoh.com
baseurl:          /
paginate:         3

author:
  name:           'Thomas Teoh'
  url:            https://www.twitter.com/tteoh
  email:          me@tteoh.com

# Custom vars
version:          1.0.0
