# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:            Thomas Teoh
tagline:          'veterinarian, research, does stuff'
description:      'Life as a veterinarian in research with a dog named Quaver.'
url:              http://www.tteoh.com
baseurl:          /
imgurl:           /public/images/
paginate:         5

author:
  name:           'Thomas Teoh'
  url:            https://www.twitter.com/tteoh
  email:          me@tteoh.com

# Custom vars
version:          1.0.0
