# Dependencies
highlighter:         rouge

# Permalinks
permalink:           pretty

# Setup
title:            Thomas Teoh
tagline:          'veterinarian, research, data, epi, also other things'
description:      'Experimenting with interesting things, and then fixing them again. Life as a different sort of veterinarian, accompanied by trusty pup Quaver.'
url:              https://tteoh.com
baseurl:          /
imgurl:           /public/images/
paginate:         5

author:
  name:           'Thomas Teoh'
  url:            https://www.twitter.com/tteoh
  email:          me@tteoh.com

# Custom vars
version:          1.0.0
