# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            tteoh
tagline:          'in which Thomas talks about things'
description:      'A sporadically updated log of thoughts and (terrible) ideas.'
url:              http://www.tteoh.com

author:
  name:           'Thomas Teoh'
  url:            https://www.twitter.com/tteoh

paginate:         5

# Custom vars
version:          1.0.0
